name: Build and test

on:
  workflow_call:

  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

    - name: Set up Ruby
      uses: ruby/setup-ruby@09c10210cc6e998d842ce8433cd9d245933cd797
      with:
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: '12'

    - name: Build and test
      run: |
        bundle exec middleman build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build
        retention-days: 1

