name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@09c10210cc6e998d842ce8433cd9d245933cd797
      with:
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: '12'

    - name: Build and test
      run: |
        bundle exec middleman build

    # Share data between the build and deploy jobs so we don't need to run `npm run build` again on deploy
    # Upload the deploy folder as an artifact so it can be downloaded and used in the deploy job
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
    # if: ${{ inputs.upload-artifact }}
      with:
          path: '.'
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
